services:
  db:
    ports: 
      - "5432:5432"
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: isdjfw8j822424dnsdf
      POSTGRES_DB: sistema_de_reservas

    volumes:
      - ./postgres-data:/var/lib/postgresql/data
